/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      label: "Table of Contents",
      id: "table-of-contents",
    },
    {
      type: "doc",
      label: "1. Preface",
      id: "preface",
    },

    // {
    //   type: 'category',
    //   label: 'Infra and System',
    //   items: [
    //     'infra-and-system/intro',
    //     'infra-and-system/technology-used/intro',
    //     //'infra-and-system/Application',
    //   ],
    // },
    {
      type: "doc",
      label: "2. Introduction",
      id: "microservices/intro",
    },
    {
      type: "category",
      label: "3. Setup",
      items: [
        "microservices/setup/getting-started",
        "microservices/setup/scaffolding",
        {
          type: "category",
          label: "3.3 Configuration",
          items: [
            "microservices/setup/configuration/intro",
            "microservices/setup/configuration/env-vars",
            "microservices/setup/configuration/static-vars",
          ],
        },
        "microservices/setup/tests",
        "microservices/setup/auto-watch",
      ],
    },
    {
      type: "doc",
      label: "4. CLI",
      id: "microservices/introduction-cli",
    },
    {
      type: "doc",
      label: "5. Swagger Specs",
      id: "microservices/swagger-specs",
    },
    {
      type: "doc",
      label: "6. Events",
      id: "microservices/events",
    },
    {
      type: "doc",
      label: "7. Workflows",
      id: "microservices/workflows",
    },
    {
      type: "category",
      label: "8. Datasources",
      items: [
        "microservices/datasources/intro",
        "microservices/datasources/api",
        "microservices/datasources/datastore",
        "microservices/datasources/kafka",
        "microservices/datasources/elasticgraph",
        "microservices/datasources/extensible-datasources",
        "microservices/datasources/aws",
        "microservices/datasources/redis",
      ],
    },
    {
      type: "doc",
      label: "9. Caching",
      id: "microservices/caching",
    },
    {
      type: "doc",
      label: "10. Mappings",
      id: "microservices/mappings",
    },
    {
      type: "doc",
      label: "11. Plugins",
      id: "microservices/plugins",
    },
    {
      type: "doc",
      label: "12. Authentication & Authorization",
      id: "microservices/authen-author",
    },
    {
      type: "doc",
      label: "13. Telemetry",
      id: "telemetry/intro",
    },
    {
      type: "doc",
      label: "14. Roadmap",
      id: "roadmap",
    },

    {
      type: "doc",
      label: "15. FAQ",
      id: "faq",
    },

    // {
    //   type: 'doc',
    //   label: 'Development Process',
    //   id: 'development-process',
    // },

    // {
    // type: 'category',
    //label: 'Out of Box',
    //  items: ['out-of-box/auto-export','out-of-box/auto-instrumentation','out-of-box/templates','out-of-box/hooks','out-of-box/dual-write'],
    // },

    // {
    //   type: 'category',
    //   label: 'Notification API Specification',
    //   items: ['notification-api'],
    // },
  ],
};

module.exports = sidebars;
