name: Pull request build check check
on:  
  pull_request:
    branches:
      - main
      
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'      
      - run: npm run build
        name: check build