name: Pull request deployment check
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_PR }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PR }}
on:  
  pull_request:
    branches:
      - main
      
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}